#!/bin/sh
PROG=configure-swes-container-tools
DESC="Configure swes-container-tools for the current host"
USAGE1="$PROG [-h|--help]"
HELP_TEXT="
        Configure the swes-container-tools package for the current host.

FILES
        <scriptdir>/.swes-container-tools.rc
            The configuration file  written by $PROG; this contains variable
            definitions used by scripts in the swes-container-tools package.

ENVIRONMENT
        Definitions for the following environment variables are written to
        the configuration file by $PROG:

        AWK
           The path to the \"awk\" utility.

        ECHO_N
           Set to \"n\" if echo_n should use \"echo -n\", or to \"c\" if
           it should use \"echo \\c\".
"
SCRIPTDIR=`cd \`dirname $0\`; pwd`
CONFIGFILE="${SCRIPTDIR}/.swes-container-tools.rc"

case $1 in
    -h|--help)
        cat <<EOF
NAME
        ${PROG} - $DESC

SYNOPSIS
        $USAGE1

DESCRIPTION$HELP_TEXT

EOF
        exit 0 ;;
    -*)
        echo "${PROG}: illegal option: $1" >&2
        echo "Usage:" >&2
        echo "  $USAGE1" >&2
        exit 1 ;;
esac

if [ ":${AWK}" = ":" ] ; then
    for AWK in awk nawk gawk false ; do
        ${AWK} 'BEGIN{exit 0}' 2>/dev/null && break
    done
    if test "${AWK}" = "false" ; then
        echo "${PROG}: cannot find awk!" >&2
        AWK=awk
    fi
fi

en_=`echo -n 1 ; echo 2`
if [ "$en_" = "12" ] ; then
   ECHO_N=n
else
   en_=`echo "1\c" ; echo 2`
   if [ "$en_" = "12" ] ; then
      ECHO_N=c
   else
      echo "${PROG}: cannot determine how to suppress echo newlines!" >&2
      ECHO_N=
   fi
fi

cat >$CONFIGFILE <<EOF
AWK=${AWK}
ECHO_N=${ECHO_N}
export AWK ECHO_N
EOF
