version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest

    steps:
      - add_ssh_keys:
          fingerprints:
            - "71:f3:13:88:05:74:a8:94:ab:70:e8:e2:5c:24:7d:a5"

      - checkout

      - setup_remote_docker

      - run:
          name: Update configuration or run tests
          command: |
              ./getTZ --dump >./zoneinfo
              install_zoneinfo=false
              if [ ! -f .zoneinfo ] ; then
                  echo "Installing missing .zoneinfo"
                  install_zoneinfo=true
              elif cmp -s zoneinfo .zoneinfo ; then
                  echo ".zoneinfo is up-to-date"
              else
                  echo "Installing newer .zoneinfo"
                  install_zoneinfo=true
              fi
              if $install_zoneinfo ; then
                  mv zoneinfo .zoneinfo
                  git config --global user.email "sweg-dev@ucar.edu"
                  git config --global user.name "SWEG CI"
                  git add .zoneinfo
                  git commit -m 'Updated .zoneinfo'
                  mkdir -p ~/.ssh/
                  echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
                  git push origin HEAD:master
                  # Quit this build
                  exit 0
              fi
              echo "Run tests"
              for baseimage in \
                  alpine:latest \
                  debian:oldstable \
                  debian:stable \
                  centos:centos7 \
                  centos:centos8 \
              ; do
                  echo $baseimage:
                  docker run --rm --volume `pwd`:/mnt $baseimage /mnt/test/runalltests.sh
                  echo
              done
                  
