version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Check environment
          command: |
              echo pwd:
              pwd
              ls -la
              echo Environment:
              printenv
              echo /etc:
              ls -l /etc
              echo /usr/share/zoneinfo:
              ls -l /usr/share/zoneinfo
