#!/bin/sh
# noOutput - Check if \$OUT file is empty
# Usage: noOutput [--error]

if [ ":$TMPDIR" = ":" ] ; then
   echo "ERROR: TMPDIR environment variable must be set" >&2
   exit 1
fi
. testutils.rc || exit 1

INFILE="${OUT}"
OUTTYPE=

case $1 in
    --error)
        INFILE="${ERR}"
        OUTTYPE="error " ;;
esac

if [ -s "${INFILE}" ] ; then
    report-message "Expected ${OUTTYPE}output to be empty, contains:" <${INFILE}
    exit 1
fi
exit 0
